add swagger, update fc
Tinhf0501/fc-management-backend pull request #16
Opened 2024-05-02 14:40 UTC by Tinhf0501

2024-05-02 15:24 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/exception/RecordNotFoundException.java
> +public class RecordNotFoundException extends Exception {
Xóa class này, đã có `BusinessException`

2024-05-02 15:26 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/annotation/ResourceType.java
> +    MediaType value() default MediaType.UNKNOWN;
Không để `default`

2024-05-02 15:26 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/annotation/ResourceTypeValidator.java
> +        this.mediaType = mediaType;
set `this.mediaType` ở dưới `initialize method`

2024-05-02 15:27 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/annotation/ResourceTypeValidator.java
> +        if (Objects.isNull(mediaType) || Objects.isNull(file))
sử dụng Stream API.

2024-05-02 15:28 UTC, suongisme commented on upload/fc/logo/44__a9b9a42b-d751-46b0-9035-e56be63c0f19.jpg
xóa toàn bộ thư mục upload

2024-05-02 15:29 UTC, suongisme requested changes
sửa lại những gì đã comment.

2024-05-02 15:31 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/annotation/BatchResourceTypeValidator.java
> +        if (files == null || files.isEmpty()) {
sử dụng `CollectionUtils.isEmpty()`

2024-05-03 02:28 UTC, Tinhf0501 commented on upload/fc/logo/44__a9b9a42b-d751-46b0-9035-e56be63c0f19.jpg
trên local k còn nên k xóa đc

2024-05-04 03:08 UTC, suongisme approved these changes
Ok

2024-05-04 03:08 UTC, merged