update code api update fc
Tinhf0501/fc-management-backend pull request #17
Opened 2024-05-06 15:34 UTC by Tinhf0501

update code api update fc (do not test, do not create job delete file)

2024-05-06 16:10 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/job/impl/JobServiceImpl.java
> +                .jobValue(JSON.stringify(jobValue))
Sao lại stringify String

2024-05-06 16:13 UTC, suongisme requested changes
Sửa lại những gì đã cmt

2024-05-07 12:45 UTC, suongisme reviewed
sửa lại những gì đã comment.

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/job/Job.java
cho toàn bộ những gì liên quan tới class này vào package `param`

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/impl/ResourceServiceImpl.java
> +        this.jobService.createJob(JSON.stringify(deleteResourceJob), JobType.DELETE_RESOURCE);
code này chạy sẽ lỗi.

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/impl/ResourceServiceImpl.java
> +        Stream.ofNullable(paths).flatMap(Collection::stream).forEach(p -> {
chỗ này không cần check null vì paths đã nonNull

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/impl/ResourceServiceImpl.java
> +                    this.jobService.createJob(JSON.stringify(deleteResourceJob), JobType.DELETE_RESOURCE);
code chạy lỗi

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/utils/CommonUtils.java
> +        str = str.replaceAll("[àáạảãâầấậẩẫăằắặẳẵ]", "a");
thao tác với String cần sử dụng `StringBuilder` hoặc `StringBuffer`

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/member/impl/MemberServiceImpl.java
> +            MemberEntity memberOnDb = this.memberRepository.findById(e.getMemberId()).orElseThrow(() -> new BusinessException(ErrorCode.NOT_FOUND_RECORD));
không nên `findById` trong vòng lặp

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/member/impl/MemberServiceImpl.java
> +            member.setCreatedBy(memberOnDb.getCreatedBy());
không cần phải `set` lại

2024-05-07 12:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/member/impl/MemberServiceImpl.java
> +            member.setCreatedDate(memberOnDb.getCreatedDate());
không cần phải set lại

2024-05-08 15:14 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/model/SearchResponse.java
trả thêm `totalPage: number` `page: number` `pageSize: number`

2024-05-08 15:17 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/football_club/request/PagingRequest.java
thêm biến `data: T` đại diện cho dữ liệu tìm kiếm

2024-05-08 15:17 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/football_club/request/SearchFcRequest.java
không extends thế này đâu.

2024-05-08 15:18 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/model/SearchResponse.java
> +    private T items;
`List<T>` không phải `T`. Search thì luôn là `List`

2024-05-08 15:19 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/football_club/IFootballClubRepository.java
> +    Page<ISearchFCResponse> search(
Truyền cả object vào. sao lại truyền lẻ tẻ thế này??

2024-05-09 01:35 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/module/resource/impl/ResourceServiceImpl.java
> +                    this.jobService.createJob(JSON.stringify(deleteResourceJob), JobType.DELETE_RESOURCE);
lỗi gì vậy ?

2024-05-09 01:36 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/utils/CommonUtils.java
> +        str = str.replaceAll("[àáạảãâầấậẩẫăằắặẳẵ]", "a");
k quan trọng đâu, nó chỉ replace nót append

2024-05-09 01:36 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/module/member/impl/MemberServiceImpl.java
> +            MemberEntity memberOnDb = this.memberRepository.findById(e.getMemberId()).orElseThrow(() -> new BusinessException(ErrorCode.NOT_FOUND_RECORD));
k nên chứ kp là k đc

2024-05-09 01:36 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/module/member/impl/MemberServiceImpl.java
> +            member.setCreatedBy(memberOnDb.getCreatedBy());
sẽ xem xét

2024-05-09 01:37 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/module/football_club/request/PagingRequest.java
T đại diện cho class hay list class đều đc

2024-05-09 01:37 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/model/SearchResponse.java
sẽ xem xét

2024-05-09 01:37 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/module/football_club/request/SearchFcRequest.java
extends Paging là đúng r seacrh nào chả có page

2024-05-09 01:37 UTC, Tinhf0501 commented on src/main/java/com/luke/fcmanagement/module/football_club/IFootballClubRepository.java
> +    Page<ISearchFCResponse> search(
lẻ tẻ tường mình hơn

2024-05-09 01:42 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/football_club/IFootballClubRepository.java
> +    Page<ISearchFCResponse> search(
Cái gì mà tường mình, chả có gì tường minh hơn ở đây cả. Với trường hợp nhiều param thì nên gom lại thành object

2024-05-09 01:42 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/football_club/request/SearchFcRequest.java
RequestPaging<SeatchObject>

2024-05-09 01:44 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/utils/CommonUtils.java
> +        str = str.replaceAll("[àáạảãâầấậẩẫăằắặẳẵ]", "a");
Nó đều tạo là string mới

2024-05-09 01:45 UTC, suongisme commented on src/main/java/com/luke/fcmanagement/module/resource/impl/ResourceServiceImpl.java
> +                    this.jobService.createJob(JSON.stringify(deleteResourceJob), JobType.DELETE_RESOURCE);
Nhìn tham số đang truyền và tham số thực tế của hàm

2024-05-12 16:04 UTC, suongisme approved these changes
ok

2024-05-12 16:04 UTC, merged